Change structure,
David-Lanzz/map-metrics pull request #2
Opened 2023-04-19 18:29 UTC by David-Lanzz

# Hello Reviewer!
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4a724d64453846675232357a676c6e6530712f67697068792e676966](https://user-images.githubusercontent.com/111298026/233167260-e16b4bb9-60c7-4f8f-88dc-412da4f3676c.gif)

I have completed all tasks assigned to me and below are some points from the work I did:👇
- Correct use of gitflow👍💯
- No linter errors👍💯
- Choosing of most fitting API👍💯
- Fetching of data from the API👍💯
- Correctly displaying relevant data from the API to the project👍💯
- Implementing of redux and react-router👍💯
- Professional documentation of readme file
- Modifying of MIT license file
And so on...,
Please let me know your insights, Thankyou!😊

2023-04-19 20:09 UTC, mckent05 requested changes
Hi @David-Lanzz, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Your project looks good and is almost ready for approveal, well done 👏 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 20:09 UTC, mckent05 commented on README.md
> +## 🚀 Live Demo <a name="live-demo"></a>
- Good job working on your project thus far, but according to the project requirements, you are required to host your project live either on Render, Netlify or GitHub pages, this would make it easier for potential recruiters to view your project. Please fix this 🙏 
- Also, you are required, according to the project requirements, to make a video, no longer than 5mins, containing a demo of the project, highlighting all the project features. Please fix this. I recommend you use Loom to make your video

2023-04-19 20:09 UTC, mckent05 commented on README.md
> +
- According to the project requirements, you are required to give credit to [Cindy Shin](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) the author of the original designed template you used, according to the creative common license. Please fix this 🙏

2023-04-19 20:09 UTC, mckent05 commented on src/components/CountryData.js
> +        <NavLink to="/" className="homekey"><i className="fa-solid fa-house home" /></NavLink>
- Good job including this button to route back to the homepage, but according to the project requirements, this button should be a `<` (back) button. Please fix this 🙏 . Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

2023-04-20 00:49 UTC, Ismailco requested changes
#### Hi @David-Lanzz, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/25227022/169399289-510de072-42e7-419b-8c2c-da9344bdd430.gif)


## Highlights

✔️ Good presentation
✔️ Clean code
✔️ Used Gitflow
✔️ Work documented professionally


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-20 00:49 UTC, Ismailco commented on README.md
> +> [Loom Presentation]("https://www.loom.com/share/1dbc6515012342daab42af84bf1180d1")
- [ ] Great work including the Live demo link and video presentation, kindly make sure that the links are accessible from the README file, as for now I can't access them from the README

2023-04-20 02:23 UTC, Reem-lab approved these changes
# Hi @David-Lanzz,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🔥🔥💯💯
<img src="https://media2.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif"/>

## Highlights 🔥🔥🔥🔥
- No Linters error ✨
- Followed Gitflow 💯🔥
- Great job working on the functionality✅
- Great job working on the filter 🤩
- Deployed well 🚀
- Good job working on the presentation video ⭐
- Professional README 💯


## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 03:11 UTC, merged